name: Deploy AlbumAPI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy AlbumAPI application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            export NODE_OPTIONS="--max-old-space-size=8192"
            git pull
            npm ci
            npm run build-prod
            cp src/index.html dist
            npm prune --production
            pm2 restart AlbumAPI
